### ISSUE TITLE
lazyXDS: App's virtualservice route rule hasn't effected while first accessing to it 

### ISSUE THREAD

**Issue by JinVei** [aeraki-mesh/aeraki#144]
**Describe the bug**
App's virtualservice route rule hasn't effected while first accessing to it 

**To Reproduce**
In my bookinfo example, i create a Virtualservice for app of Reviews like below:

Virtualservices:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: reviews
  namespace: default
spec:
  hosts:
  - reviews
  http:
  - route:
    - destination:
        host: reviews
        subset: v1
      weight: 50
    - destination:
        host: reviews
        subset: v3
      weight: 50
```
So in an ideal situation, the traffic to Reviews should never route to the v2 version. But it does unexpected traffic to v2 version of Reviews during first accessing to.

**Additional context**
May useful references:
https://istio.io/latest/docs/ops/common-problems/network-issues/#route-rules-have-no-effect-on-ingress-gateway-requests
