### ISSUE TITLE
metaprotocol router match error

### ISSUE THREAD

**Issue by scaat** [aeraki-mesh/aeraki#160]
**Describe the bug**
When I use metaprotocol, when the route matching condition is multiple, it is reflected as an OR relationship. When dumping the configuration, it is found that the delivery rules and the configuration rules are inconsistent.

**To Reproduce**
configure rule is:
```
  routes:
    - name: traffic-spilt
      match:
        attributes:
          method:
            exact: sayHello
          interface:
            exact: org.apache.dubbo.samples.basic.api.DemoService11
      route:
        - destination:
            host: demoservice.mesh.yonghui.cn
            subset: v2
```
dump config rule is: 
```
      "routes": [
       {
        "name": "traffic-spilt",
        "match": {
         "metadata": [
          {
           "name": "method",
           "exact_match": "sayHello"
          },
          {
           "name": "method",
           "exact_match": "sayHello"
          }
         ]
        },
```

**Expected behavior**
The configuration rules are consistent with the delivery rules.

**Screenshots**

**Additional context**
